volumes:
  n8n_storage:
  postgres_storage:

networks:
  n8n-local:
    name: n8n-local

services:
  postgres:
    image: postgres:latest
    networks: ['n8n-local']
    restart: unless-stopped
    ports:
      - 5433:5432  # Changed from 15432 to 5433 to avoid conflicts
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER=${POSTGRES_NON_ROOT_USER:-n8n}
      - POSTGRES_NON_ROOT_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD:-n8n}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    image: n8nio/n8n:latest
    networks: ['n8n-local']
    container_name: n8n-bookoly
    restart: unless-stopped
    ports:
      - 5679:5678  # Changed from 5678:5678 to avoid port conflict
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432  # Added explicit port
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_HOST=0.0.0.0  # Changed from localhost to 0.0.0.0
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - N8N_EDITOR_BASE_URL=http://localhost:5679  # Add this to specify the editor URL
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - NODE_FUNCTION_ALLOW_EXTERNAL=*
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom/node_modules/custom_nodes
      - BOOKOLY_BASE_URL=${BOOKOLY_BASE_URL}
    links:
      - postgres
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./dist:/home/node/.n8n/custom/node_modules/custom_nodes
    depends_on:
      postgres:
        condition: service_healthy

