export interface Option {
	name: string;
	value: string;
}

export const voiceOptions: Option[] = [
	{ value: 'l1zE9xgNpUTaQCZzpNJa', name: 'Alberto' },
	{ value: 'kdmDKE6EkgrWrrykO9Qt', name: 'Alexandra' },
	{ value: 'Xb7hH8MSUJpSbSDYk0k2', name: 'Alice' },
	{ value: 'xctasy8XvGp2cVO9HL9k', name: 'Allison' },
	{ value: 'alloy', name: 'Alloy' },
	{ value: '1tyCkDKmBd1gCvRcimhT', name: 'Amitabh' },
	{ value: '9BWtsMINqrJLrRacOk9x', name: 'Aria' },
	{ value: 'ash', name: 'Ash' },
	{ value: 'pqHfZKP75CvOlQylNhV4', name: 'Bill' },
	{ value: 'nPczCjzI2devNBz1zQrb', name: 'Brian' },
	{ value: 'N2lVS1w4EtoT3dr4eOWO', name: 'Callum' },
	{ value: 'IKne3meq5aSn9XLyUdCD', name: 'Charlie' },
	{ value: 'XB0fDUnXU5powFXDhCwa', name: 'Charlotte' },
	{ value: 'iP95p4xoKVk53GoZ742B', name: 'Chris' },
	{ value: 'coral', name: 'Coral' },
	{ value: '9F4C8ztpNUmXkdDDbz3J', name: 'Dan' },
	{ value: 'onwK4e9ZLuTAKqWW03F9', name: 'Daniel' },
	{ value: 'echo', name: 'Echo' },
	{ value: 'cjVigY5qzO86Huf0OWal', name: 'Eric' },
	{ value: 'fable', name: 'Fable' },
	{ value: 'JBFqnCBsd6RMkjVDRZzb', name: 'George' },
	{ value: 'OYTbf65OHHFELVut7v2H', name: 'Hope' },
	{ value: 'cgSgspJ2msm6clMCkdW9', name: 'Jessica' },
	{ value: 'XopCoWNooN3d7LfWZyX5', name: 'Krishna' },
	{ value: 'FGY2WhTYpPnrIDTdsKH5', name: 'Laura' },
	{ value: 'TX3LPaxmHKxFdv7VOQHJ', name: 'Liam' },
	{ value: 'pFZP5JQG7iQjIQuC4Bku', name: 'Lily' },
	{ value: 'UgBBYS2sOqTuMpoF3BR0', name: 'Mark' },
	{ value: 'XrExE9yKIg1WjnnlVkGX', name: 'Matilda' },
	{ value: 'nova', name: 'Nova' },
	{ value: 'onyx', name: 'Onyx' },
	{ value: 'LHgFk7RaIiyNE5I3pC1d', name: 'Rachel' },
	{ value: 'VOJyehUzZPmLbl8DHdih', name: 'Richard' },
	{ value: 'SAz9YHcvj6GT2YYXdXww', name: 'River' },
	{ value: 'CwhRBWXzGAHq8TQ4Fs17', name: 'Roger' },
	{ value: 'sage', name: 'Sage' },
	{ value: 'KHCvMklQZZo0O30ERnVn', name: 'Sara' },
	{ value: 'EXAVITQu4vr4xnSDxMaL', name: 'Sarah' },
	{ value: 'shimmer', name: 'Shimmer' },
	{ value: '8l89UrPQsmYVJoJRfnAt', name: 'Vikram' },
	{ value: 'bIHbv24MWmeRgasZH58o', name: 'Will' },
	{ value: 'w2yzW27GeWlJ26peMH9t', name: 'Yash' },
];

export const languageOptions: Option[] = [
	{ value: 'af', name: 'Afrikaans' },
	{ value: 'ar', name: 'Arabic' },
	{ value: 'hy', name: 'Armenian' },
	{ value: 'az', name: 'Azerbaijani' },
	{ value: 'be', name: 'Belarusian' },
	{ value: 'bs', name: 'Bosnian' },
	{ value: 'bg', name: 'Bulgarian' },
	{ value: 'ca', name: 'Catalan' },
	{ value: 'zh', name: 'Chinese' },
	{ value: 'hr', name: 'Croatian' },
	{ value: 'cs', name: 'Czech' },
	{ value: 'da', name: 'Danish' },
	{ value: 'nl', name: 'Dutch' },
	{ value: 'en', name: 'English' },
	{ value: 'et', name: 'Estonian' },
	{ value: 'fi', name: 'Finnish' },
	{ value: 'fr', name: 'French' },
	{ value: 'gl', name: 'Galician' },
	{ value: 'de', name: 'German' },
	{ value: 'el', name: 'Greek' },
	{ value: 'he', name: 'Hebrew' },
	{ value: 'hi', name: 'Hindi' },
	{ value: 'hu', name: 'Hungarian' },
	{ value: 'is', name: 'Icelandic' },
	{ value: 'id', name: 'Indonesian' },
	{ value: 'it', name: 'Italian' },
	{ value: 'ja', name: 'Japanese' },
	{ value: 'kn', name: 'Kannada' },
	{ value: 'kk', name: 'Kazakh' },
	{ value: 'ko', name: 'Korean' },
	{ value: 'lv', name: 'Latvian' },
	{ value: 'lt', name: 'Lithuanian' },
	{ value: 'mk', name: 'Macedonian' },
	{ value: 'ms', name: 'Malay' },
	{ value: 'mr', name: 'Marathi' },
	{ value: 'mi', name: 'Maori' },
	{ value: 'ne', name: 'Nepali' },
	{ value: 'no', name: 'Norwegian' },
	{ value: 'fa', name: 'Persian' },
	{ value: 'pl', name: 'Polish' },
	{ value: 'pt', name: 'Portuguese' },
	{ value: 'ro', name: 'Romanian' },
	{ value: 'ru', name: 'Russian' },
	{ value: 'sr', name: 'Serbian' },
	{ value: 'sk', name: 'Slovak' },
	{ value: 'sl', name: 'Slovenian' },
	{ value: 'es', name: 'Spanish' },
	{ value: 'sw', name: 'Swahili' },
	{ value: 'sv', name: 'Swedish' },
	{ value: 'tl', name: 'Tagalog' },
	{ value: 'ta', name: 'Tamil' },
	{ value: 'th', name: 'Thai' },
	{ value: 'tr', name: 'Turkish' },
	{ value: 'uk', name: 'Ukrainian' },
	{ value: 'ur', name: 'Urdu' },
	{ value: 'vi', name: 'Vietnamese' },
	{ value: 'cy', name: 'Welsh' },
];

export const translationLanguageOptions: Option[] = [
	{ value: '', name: 'Empty' },
	{ value: 'ar', name: 'Arabic' },
	{ value: 'bn', name: 'Bengali' },
	{ value: 'ca', name: 'Catalan' },
	{ value: 'zh-Hans', name: 'Chinese (Simplified)' },
	{ value: 'zh-Hant', name: 'Chinese (Traditional)' },
	{ value: 'da', name: 'Danish' },
	{ value: 'nl', name: 'Dutch' },
	{ value: 'en', name: 'English' },
	{ value: 'fi', name: 'Finnish' },
	{ value: 'fr', name: 'French' },
	{ value: 'de', name: 'German' },
	{ value: 'el', name: 'Greek' },
	{ value: 'hi', name: 'Hindi' },
	{ value: 'hi-Latn', name: 'Hindi (Latin)' },
	{ value: 'id', name: 'Indonesian' },
	{ value: 'it', name: 'Italian' },
	{ value: 'ja', name: 'Japanese' },
	{ value: 'ko', name: 'Korean' },
	{ value: 'ms', name: 'Malay' },
	{ value: 'zh', name: 'Mandarin Chinese' },
	{ value: 'pt', name: 'Portuguese' },
	{ value: 'pt-BR', name: 'Portuguese (Brazil)' },
	{ value: 'ru', name: 'Russian' },
	{ value: 'es', name: 'Spanish' },
	{ value: 'es-419', name: 'Spanish (Latin America)' },
	{ value: 'sv', name: 'Swedish' },
	{ value: 'th', name: 'Thai' },
	{ value: 'tr', name: 'Turkish' },
	{ value: 'uk', name: 'Ukrainian' },
	{ value: 'vi', name: 'Vietnamese' },
];

export const subtitleStyleOptions: Option[] = [
	{ value: 'simple', name: 'Simple' },
	{ value: 'signal', name: 'Signal' },
	{ value: 'rainbow', name: 'Rainbow' },
	{ value: 'highlight_current_word', name: 'Highlight Current Word' },
	{ value: 'signal_highlight_current_word', name: 'Signal Highlight Current Word' },
	{ value: 'rainbow_highlight_current_word', name: 'Rainbow Highlight Current Word' },
];

export const fontFamilyOptions: Option[] = [
	{ value: 'Arial', name: 'Arial' },
	{ value: 'Charm', name: 'Charm' },
	{ value: 'Eagle Lake', name: 'Eagle Lake' },
	{ value: 'Libre Baskerville', name: 'Libre Baskerville' },
	{ value: 'Lobster', name: 'Lobster' },
	{ value: 'Luckiest Guy', name: 'Luckiest Guy' },
	{ value: 'Marck Script', name: 'Marck Script' },
	{ value: 'Nanum Pen Script', name: 'Nanum Pen Script' },
	{ value: 'Nunito', name: 'Nunito' },
	{ value: 'Pacifico', name: 'Pacifico' },
	{ value: 'Roboto', name: 'Roboto' },
	{ value: 'Korean', name: 'Korean' },
	{ value: 'Korean Bold', name: 'Korean Bold' },
	{ value: 'Chinese Simplified', name: 'Chinese Simplified' },
	{ value: 'Chinese Traditional', name: 'Chinese Traditional' },
];

export const positionOptions: Option[] = [
	{ value: 'top_left', name: 'Top Left' },
	{ value: 'top_center', name: 'Top Center' },
	{ value: 'top_right', name: 'Top Right' },
	{ value: 'center_left', name: 'Center Left' },
	{ value: 'center_center', name: 'Center Center' },
	{ value: 'center_right', name: 'Center Right' },
	{ value: 'bottom_left', name: 'Bottom Left' },
	{ value: 'bottom_center', name: 'Bottom Center' },
	{ value: 'bottom_right', name: 'Bottom Right' },
	{ value: 'mid_top_center', name: 'Mid Top Center' },
	{ value: 'mid_bottom_center', name: 'Mid Bottom Center' },
];
export const resolutionOptions: Option[] = [
	{ value: 'horizontal_hd', name: 'Horizontal - 1080p (HD): 1920x1080' },
	{ value: 'horizontal_2k', name: 'Horizontal - 1440p (2K): 2560x1440' },
	{ value: 'horizontal_4k', name: 'Horizontal - 2160p (4K): 3840x2160' },
	{ value: 'vertical_hd', name: 'Vertical - 1080p (HD): 1080x1920' },
	{ value: 'vertical_2k', name: 'Vertical - 1440p (2K): 1440x2560' },
	{ value: 'vertical_4k', name: 'Vertical - 2160p (4K): 2160x3840' },
	{ value: 'square_hd', name: 'Square - 1080p (HD): 1080x1080' },
	{ value: 'square_2k', name: 'Square - 1440p (2K): 1440x1440' },
	{ value: 'square_4k', name: 'Square - 2160p (4K): 2160x2160' },
];
