import {
	FontFamily,
	Language,
	Option,
	SubtitlePosition,
	SubtitleStyle,
	TranslationLanguage,
	VideoResolution,
	Voice,
} from '../types';

export const voiceOptions: Option[] = [
	{ value: Voice.ALBERTO, name: 'Alberto' },
	{ value: Voice.ALEXANDRA, name: 'Alexandra' },
	{ value: Voice.ALICE, name: 'Alice' },
	{ value: Voice.ALLISON, name: 'Allison' },
	{ value: Voice.ALLOY, name: 'Alloy' },
	{ value: Voice.AMITABH, name: 'Amitabh' },
	{ value: Voice.ARIA, name: 'Aria' },
	{ value: Voice.ASH, name: 'Ash' },
	{ value: Voice.BILL, name: 'Bill' },
	{ value: Voice.BRIAN, name: 'Brian' },
	{ value: Voice.CALLUM, name: 'Callum' },
	{ value: Voice.CHARLIE, name: 'Charlie' },
	{ value: Voice.CHARLOTTE, name: 'Charlotte' },
	{ value: Voice.CHRIS, name: 'Chris' },
	{ value: Voice.CORAL, name: 'Coral' },
	{ value: Voice.DAN, name: 'Dan' },
	{ value: Voice.DANIEL, name: 'Daniel' },
	{ value: Voice.ECHO, name: 'Echo' },
	{ value: Voice.ERIC, name: 'Eric' },
	{ value: Voice.FABLE, name: 'Fable' },
	{ value: Voice.GEORGE, name: 'George' },
	{ value: Voice.HOPE, name: 'Hope' },
	{ value: Voice.JESSICA, name: 'Jessica' },
	{ value: Voice.KRISHNA, name: 'Krishna' },
	{ value: Voice.LAURA, name: 'Laura' },
	{ value: Voice.LIAM, name: 'Liam' },
	{ value: Voice.LILY, name: 'Lily' },
	{ value: Voice.MARK, name: 'Mark' },
	{ value: Voice.MATILDA, name: 'Matilda' },
	{ value: Voice.NONE, name: 'None' },
	{ value: Voice.NOVA, name: 'Nova' },
	{ value: Voice.ONYX, name: 'Onyx' },
	{ value: Voice.RACHEL, name: 'Rachel' },
	{ value: Voice.RICHARD, name: 'Richard' },
	{ value: Voice.RIVER, name: 'River' },
	{ value: Voice.ROGER, name: 'Roger' },
	{ value: Voice.SAGE, name: 'Sage' },
	{ value: Voice.SARA, name: 'Sara' },
	{ value: Voice.SARAH, name: 'Sarah' },
	{ value: Voice.SHIMMER, name: 'Shimmer' },
	{ value: Voice.VIKRAM, name: 'Vikram' },
	{ value: Voice.WILL, name: 'Will' },
	{ value: Voice.YASH, name: 'Yash' },
];

export const languageOptions: Option[] = [
	{ value: Language.AF, name: 'Afrikaans' },
	{ value: Language.AR, name: 'Arabic' },
	{ value: Language.HY, name: 'Armenian' },
	{ value: Language.AZ, name: 'Azerbaijani' },
	{ value: Language.BE, name: 'Belarusian' },
	{ value: Language.BS, name: 'Bosnian' },
	{ value: Language.BG, name: 'Bulgarian' },
	{ value: Language.CA, name: 'Catalan' },
	{ value: Language.ZH, name: 'Chinese' },
	{ value: Language.HR, name: 'Croatian' },
	{ value: Language.CS, name: 'Czech' },
	{ value: Language.DA, name: 'Danish' },
	{ value: Language.NL, name: 'Dutch' },
	{ value: Language.EN, name: 'English' },
	{ value: Language.ET, name: 'Estonian' },
	{ value: Language.FI, name: 'Finnish' },
	{ value: Language.FR, name: 'French' },
	{ value: Language.GL, name: 'Galician' },
	{ value: Language.DE, name: 'German' },
	{ value: Language.EL, name: 'Greek' },
	{ value: Language.HE, name: 'Hebrew' },
	{ value: Language.HI, name: 'Hindi' },
	{ value: Language.HU, name: 'Hungarian' },
	{ value: Language.IS, name: 'Icelandic' },
	{ value: Language.ID, name: 'Indonesian' },
	{ value: Language.IT, name: 'Italian' },
	{ value: Language.JA, name: 'Japanese' },
	{ value: Language.KN, name: 'Kannada' },
	{ value: Language.KK, name: 'Kazakh' },
	{ value: Language.KO, name: 'Korean' },
	{ value: Language.LV, name: 'Latvian' },
	{ value: Language.LT, name: 'Lithuanian' },
	{ value: Language.MK, name: 'Macedonian' },
	{ value: Language.MS, name: 'Malay' },
	{ value: Language.MR, name: 'Marathi' },
	{ value: Language.MI, name: 'Maori' },
	{ value: Language.NE, name: 'Nepali' },
	{ value: Language.NO, name: 'Norwegian' },
	{ value: Language.FA, name: 'Persian' },
	{ value: Language.PL, name: 'Polish' },
	{ value: Language.PT, name: 'Portuguese' },
	{ value: Language.RO, name: 'Romanian' },
	{ value: Language.RU, name: 'Russian' },
	{ value: Language.SR, name: 'Serbian' },
	{ value: Language.SK, name: 'Slovak' },
	{ value: Language.SL, name: 'Slovenian' },
	{ value: Language.ES, name: 'Spanish' },
	{ value: Language.SW, name: 'Swahili' },
	{ value: Language.SV, name: 'Swedish' },
	{ value: Language.TL, name: 'Tagalog' },
	{ value: Language.TA, name: 'Tamil' },
	{ value: Language.TH, name: 'Thai' },
	{ value: Language.TR, name: 'Turkish' },
	{ value: Language.UK, name: 'Ukrainian' },
	{ value: Language.UR, name: 'Urdu' },
	{ value: Language.VI, name: 'Vietnamese' },
	{ value: Language.CY, name: 'Welsh' },
];

export const translationLanguageOptions: Option[] = [
	{ value: TranslationLanguage.NONE, name: 'No Translation' },
	{ value: TranslationLanguage.AR, name: 'Arabic' },
	{ value: TranslationLanguage.BN, name: 'Bengali' },
	{ value: TranslationLanguage.CA, name: 'Catalan' },
	{ value: TranslationLanguage.ZH_HANS, name: 'Chinese (Simplified)' },
	{ value: TranslationLanguage.ZH_HANT, name: 'Chinese (Traditional)' },
	{ value: TranslationLanguage.DA, name: 'Danish' },
	{ value: TranslationLanguage.NL, name: 'Dutch' },
	{ value: TranslationLanguage.EN, name: 'English' },
	{ value: TranslationLanguage.FI, name: 'Finnish' },
	{ value: TranslationLanguage.FR, name: 'French' },
	{ value: TranslationLanguage.DE, name: 'German' },
	{ value: TranslationLanguage.EL, name: 'Greek' },
	{ value: TranslationLanguage.HI, name: 'Hindi' },
	{ value: TranslationLanguage.HI_LATN, name: 'Hindi (Latin)' },
	{ value: TranslationLanguage.ID, name: 'Indonesian' },
	{ value: TranslationLanguage.IT, name: 'Italian' },
	{ value: TranslationLanguage.JA, name: 'Japanese' },
	{ value: TranslationLanguage.KO, name: 'Korean' },
	{ value: TranslationLanguage.MS, name: 'Malay' },
	{ value: TranslationLanguage.ZH, name: 'Mandarin Chinese' },
	{ value: TranslationLanguage.PT, name: 'Portuguese' },
	{ value: TranslationLanguage.PT_BR, name: 'Portuguese (Brazil)' },
	{ value: TranslationLanguage.RU, name: 'Russian' },
	{ value: TranslationLanguage.ES, name: 'Spanish' },
	{ value: TranslationLanguage.ES_419, name: 'Spanish (Latin America)' },
	{ value: TranslationLanguage.SV, name: 'Swedish' },
	{ value: TranslationLanguage.TH, name: 'Thai' },
	{ value: TranslationLanguage.TR, name: 'Turkish' },
	{ value: TranslationLanguage.UK, name: 'Ukrainian' },
	{ value: TranslationLanguage.VI, name: 'Vietnamese' },
];

export const subtitleStyleOptions: Option[] = [
	{ value: SubtitleStyle.SIMPLE, name: 'Simple' },
	{ value: SubtitleStyle.SIGNAL, name: 'Signal' },
	{ value: SubtitleStyle.RAINBOW, name: 'Rainbow' },
	{ value: SubtitleStyle.HIGHLIGHT_CURRENT_WORD, name: 'Highlight Current Word' },
	{
		value: SubtitleStyle.SIGNAL_HIGHLIGHT_CURRENT_WORD,
		name: 'Signal Highlight Current Word',
	},
	{
		value: SubtitleStyle.RAINBOW_HIGHLIGHT_CURRENT_WORD,
		name: 'Rainbow Highlight Current Word',
	},
];

export const fontFamilyOptions: Option[] = [
	{ value: FontFamily.ARIAL, name: 'Arial' },
	{ value: FontFamily.CHARM, name: 'Charm' },
	{ value: FontFamily.EAGLE_LAKE, name: 'Eagle Lake' },
	{ value: FontFamily.LIBRE_BASKERVILLE, name: 'Libre Baskerville' },
	{ value: FontFamily.LOBSTER, name: 'Lobster' },
	{ value: FontFamily.LUCKIEST_GUY, name: 'Luckiest Guy' },
	{ value: FontFamily.MARCK_SCRIPT, name: 'Marck Script' },
	{ value: FontFamily.NANUM_PEN_SCRIPT, name: 'Nanum Pen Script' },
	{ value: FontFamily.NUNITO, name: 'Nunito' },
	{ value: FontFamily.PACIFICO, name: 'Pacifico' },
	{ value: FontFamily.ROBOTO, name: 'Roboto' },
	{ value: FontFamily.KOREAN, name: 'Korean' },
	{ value: FontFamily.KOREAN_BOLD, name: 'Korean Bold' },
	{ value: FontFamily.CHINESE_SIMPLIFIED, name: 'Chinese Simplified' },
	{ value: FontFamily.CHINESE_TRADITIONAL, name: 'Chinese Traditional' },
];

export const positionOptions: Option[] = [
	{ value: SubtitlePosition.TOP_LEFT, name: 'Top Left' },
	{ value: SubtitlePosition.TOP_CENTER, name: 'Top Center' },
	{ value: SubtitlePosition.TOP_RIGHT, name: 'Top Right' },
	{ value: SubtitlePosition.CENTER_LEFT, name: 'Center Left' },
	{ value: SubtitlePosition.CENTER_CENTER, name: 'Center Center' },
	{ value: SubtitlePosition.CENTER_RIGHT, name: 'Center Right' },
	{ value: SubtitlePosition.BOTTOM_LEFT, name: 'Bottom Left' },
	{ value: SubtitlePosition.BOTTOM_CENTER, name: 'Bottom Center' },
	{ value: SubtitlePosition.BOTTOM_RIGHT, name: 'Bottom Right' },
	{ value: SubtitlePosition.MID_TOP_CENTER, name: 'Mid Top Center' },
	{ value: SubtitlePosition.MID_BOTTOM_CENTER, name: 'Mid Bottom Center' },
];

export const resolutionOptions: Option[] = [
	{ value: VideoResolution.HORIZONTAL_HD, name: 'Horizontal: Full HD (1920x1080)' },
	{ value: VideoResolution.HORIZONTAL_2K, name: 'Horizontal: 2K (2560x1440)' },
	{ value: VideoResolution.HORIZONTAL_4K, name: 'Horizontal: 4K (3840x2160)' },
	{ value: VideoResolution.VERTICAL_HD, name: 'Vertical: Full HD (1080x1920)' },
	{ value: VideoResolution.VERTICAL_2K, name: 'Vertical: 2K (1440x2560)' },
	{ value: VideoResolution.VERTICAL_4K, name: 'Vertical: 4K (2160x3840)' },
	{ value: VideoResolution.SQUARE_HD, name: 'Square: Full HD (1080x1080)' },
	{ value: VideoResolution.SQUARE_2K, name: 'Square: 2K (1440x1440)' },
	{ value: VideoResolution.SQUARE_4K, name: 'Square: 4K (2160x2160)' },
];
