import { BookolyResourceDefinition, BookolyResourceType } from '../types';
import { getSubtitleParameters } from './subtitleParams';
import {
	getNameParam,
	getUrlParam,
	getWebhookUrlParam,
	getVoiceParam,
	getIdParam,
	getResolutionParam,
	getMuteParam,
	getTypeParam,
	getSubtitleUrlParam,
	getSecParam,
	getTextParam,
	getRotateParam,
	getWaitParam,
} from './commonParams';
import { scenesParam } from './videoParams/scenes';
import { watermarkUrlParam, watermarkPositionParam } from './videoParams/watermark';
import { blurOptionParam } from './videoParams/blur';
import { clipOptionParam } from './videoParams/clip';
import {
	xCoordinateParam,
	yCoordinateParam,
	cropWidthParam,
	cropHeightParam,
} from './videoParams/crop';
import { audioUrlParam, trimAudioParam, audioVolumeParam } from './videoParams/audio';
import { splitOptionParams } from './videoParams/split';

export const videoResource: BookolyResourceDefinition = {
	displayName: 'Video',
	value: BookolyResourceType.Video,
	description: 'Manage video operations',
	operations: [
		{
			displayName: 'Operation',
			name: 'operation',
			type: 'options',
			noDataExpression: true,
			displayOptions: {
				show: {
					resource: [BookolyResourceType.Video],
				},
			},
			options: [
				{
					name: 'Add Audio to Video',
					value: 'addAudioToVideo',
					description: 'Seamlessly add audio tracks to your video',
					action: 'Add audio to a video',
				},
				{
					name: 'Add Audio with Subtitle to Video',
					value: 'addAudioWithSubtitlesToVideo',
					description:
						'Adds audio to your video and automatically generates and adds subtitles from the audio',
					action: 'Add audio with subtitles to a video',
				},
				{
					name: 'Add Subtitles to a Video From a File',
					value: 'addSubtitlesToVideoFromFile',
					description: 'Automatically generates and adds subtitles to your video',
					action: 'Add subtitles to a video from a file',
				},
				{
					name: 'Add Subtitles to Video',
					value: 'addSubtitlesToVideo',
					description: 'Automatically generates and adds subtitles to your video',
					action: 'Add subtitles to a video',
				},
				{
					name: 'Add Watermark to a Video',
					value: 'addWatermarkToVideo',
					description: 'Places an image as a watermark on the video at specified coordinates',
					action: 'Add a watermark to a video',
				},
				{
					name: 'Blur a Video',
					value: 'blurVideo',
					description: 'Apply a blur effect to a specific area of a video',
					action: 'Blur a video',
				},
				{
					name: 'Clip A Video',
					value: 'clipVideo',
					description: 'Extract a clip from a video using a start time and duration',
					action: 'Clip a video',
				},
				{
					name: 'Create a Slideshow',
					value: 'createSlideshow',
					description: 'Creates a video slideshow from images, videos, or a combination of both',
					action: 'Create a slideshow from a list of images',
				},
				{
					name: 'Crop a Video',
					value: 'cropVideo',
					description: 'Crops the video to a specific area using custom coordinates and dimensions',
					action: 'Crop a video',
				},
				{
					name: 'Extract Audio From Video',
					value: 'extractAudioFromVideo',
					description: 'Separates and saves the audio track from a video file',
					action: 'Extract audio from a video',
				},
				{
					name: 'Frame a Video',
					value: 'frameVideo',
					description:
						'Extract a single frame from a video at a specified timestamp and save it as an image',
					action: 'Frame a video',
				},
				{
					name: 'Generate Video',
					value: 'generateVideo',
					description:
						'Create a video from images and video clips, generate and add a voice-over with automated subtitles, and integrate background music',
					action: 'Generate a video',
				},
				{
					name: 'Mute a Video',
					value: 'muteVideo',
					description: "Mute the video's audio by reducing the volume to zero",
					action: 'Mute a video by reducing the volume to zero',
				},
				{
					name: 'Rotate a Video',
					value: 'rotateVideo',
					description: 'Rotate a video by 90, 180, or 270 degrees clockwise',
					action: 'Rotate a video',
				},
				{
					name: 'Split Video Into Scenes',
					value: 'splitVideoIntoScenes',
					description:
						'Automatically divide a video into multiple segments based on scene detection or fixed intervals',
					action: 'Split a video into scenes',
				},
				{
					name: 'Wait for Video Generation',
					value: 'waitForVideoGeneration',
					description: 'Pauses the workflow until the video generation process is finished',
					action: 'Pauses the workflow until the video generation process is finished',
				},
			],
			default: 'generateVideo',
		},
	],
	parameters: [
		getIdParam(
			'waitForVideoGeneration',
			BookolyResourceType.Video,
			'videoId',
			'Video ID',
			'The ID of the video',
		),
		getNameParam(
			[
				'addAudioToVideo',
				'addAudioWithSubtitlesToVideo',
				'addSubtitlesToVideoFromFile',
				'addSubtitlesToVideo',
				'addWatermarkToVideo',
				'blurVideo',
				'clipVideo',
				'createSlideshow',
				'cropVideo',
				'extractAudioFromVideo',
				'frameVideo',
				'generateVideo',
				'muteVideo',
				'rotateVideo',
				'splitVideoIntoScenes',
			],
			BookolyResourceType.Video,
			'The name of the video',
		),
		getUrlParam(
			[
				'addAudioToVideo',
				'addAudioWithSubtitlesToVideo',
				'addSubtitlesToVideoFromFile',
				'addSubtitlesToVideo',
				'addWatermarkToVideo',
				'blurVideo',
				'clipVideo',
				'cropVideo',
				'extractAudioFromVideo',
				'frameVideo',
				'muteVideo',
				'rotateVideo',
				'splitVideoIntoScenes',
			],
			BookolyResourceType.Video,
			true,
			'The URL of the video',
		),
		getMuteParam(
			[
				'addAudioToVideo',
				'addAudioWithSubtitlesToVideo',
				'addWatermarkToVideo',
				'blurVideo',
				'clipVideo',
				'cropVideo',
				'rotateVideo',
				'splitVideoIntoScenes',
			],
			BookolyResourceType.Video,
		),
		getWebhookUrlParam(
			[
				'addAudioToVideo',
				'addAudioWithSubtitlesToVideo',
				'addSubtitlesToVideoFromFile',
				'addSubtitlesToVideo',
				'addWatermarkToVideo',
				'blurVideo',
				'clipVideo',
				'createSlideshow',
				'cropVideo',
				'extractAudioFromVideo',
				'frameVideo',
				'generateVideo',
				'muteVideo',
				'rotateVideo',
				'splitVideoIntoScenes',
			],
			BookolyResourceType.Video,
			'webhook_url',
			'Enter a valid URL to receive webhook notifications. Video ID and URL will be included.',
		),
		getResolutionParam(['createSlideshow', 'generateVideo'], BookolyResourceType.Video),
		getTextParam(
			['generateVideo'],
			BookolyResourceType.Video,
			true,
			'The text to create the speech synthesis from',
		),
		getVoiceParam('generateVideo', BookolyResourceType.Video, true, 'The name of the voice'),
		getTypeParam(['addSubtitlesToVideoFromFile'], BookolyResourceType.Video),
		getSubtitleUrlParam(
			['addSubtitlesToVideoFromFile'],
			BookolyResourceType.Video,
			true,
			'The URL of the subtitle file',
		),
		getSecParam(['frameVideo'], BookolyResourceType.Video),
		getRotateParam(['rotateVideo'], BookolyResourceType.Video),
		// Extracted unique/complex parameter groups
		audioUrlParam,
		trimAudioParam,
		audioVolumeParam,
		scenesParam,
		watermarkUrlParam,
		watermarkPositionParam,
		clipOptionParam,
		xCoordinateParam,
		yCoordinateParam,
		cropWidthParam,
		cropHeightParam,
		// Subtitle parameters for relevant operations
		...blurOptionParam,
		...splitOptionParams,
		...getSubtitleParameters('addAudioWithSubtitlesToVideo'),
		...getSubtitleParameters('addSubtitlesToVideo'),
		...getSubtitleParameters('generateVideo'),
		getWaitParam(
			[
				'addAudioToVideo',
				'addAudioWithSubtitlesToVideo',
				'addSubtitlesToVideoFromFile',
				'addSubtitlesToVideo',
				'addWatermarkToVideo',
				'blurVideo',
				'clipVideo',
				'createSlideshow',
				'cropVideo',
				'extractAudioFromVideo',
				'frameVideo',
				'generateVideo',
				'muteVideo',
				'rotateVideo',
				'splitVideoIntoScenes',
			],
			BookolyResourceType.Video,
			'If enabled, the node will poll the server until the video is finished and then return the full video object instead of just the creation response',
		),
	],
};
